[tools]
python = "3.13.1"
uv = "latest"
ruff = "latest"
node = "22.12.0"
ocaml = "4.14.2"
opam = "2.3.0"
swiprolog = "9.2.9"
julia = "1.11.5"
crystal = "1.18.2"
clojure = "1.12.3.1577"
leiningen = "2.12.0"
