name: haskell

on:
  push:
    paths:
      - 'haskell/**'
    branches:
      - main
  pull_request:
    paths:
      - 'haskell/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: haskell-actions/setup@v2
      with:
        ghc-version: 9.6.7
        enable-stack: true
        stack-version: 3.3.1
    - run: stack test
